# The Hello World of Deep Learning with Neural Networks
Course 1 - Week 1

This code based over the code provided during the:

**Tensorflow in Practice** - Coursera Specialization.

Original code repo: https://github.com/lmoroney/dlaicourse

To maximize the learning all the notebooks will be modified to use different dataset by keeping the underling goals. Finally, the ultimate goal is to learn best practices in the usage of TF an not to obtain for each notebook the best possible model.

## Imports

In [1]:
import tensorflow as tf
import numpy as np


#extract keras
from tensorflow import keras

# additional libs
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

## Providing data

In [2]:
df = pd.read_csv("data/avocado.csv", index_col=0)

In [3]:
df.head()

Date  AveragePrice  Total Volume     4046       4225    4770  \
0  2015-12-27          1.33      64236.62  1036.74   54454.85   48.16   
1  2015-12-20          1.35      54876.98   674.28   44638.81   58.33   
2  2015-12-13          0.93     118220.22   794.70  109149.67  130.50   
3  2015-12-06          1.08      78992.15  1132.00   71976.41   72.58   
4  2015-11-29          1.28      51039.60   941.48   43838.39   75.78   

   Total Bags  Small Bags  Large Bags  XLarge Bags          type  year  region  
0     8696.87     8603.62       93.25          0.0  conventional  2015  Albany  
1     9505.56     9408.07       97.49          0.0  conventional  2015  Albany  
2     8145.35     8042.21      103.14          0.0  conventional  2015  Albany  
3     5811.16     5677.40      133.76          0.0  conventional  2015  Albany  
4     6183.95     5986.26      197.69          0.0  conventional  2015  Albany

Kaggle dataset: https://www.kaggle.com/neuromusic/avocado-prices

Some relevant columns in the dataset:

- Date - The date of the observation
- AveragePrice - the average price of a single avocado
- type - conventional or organic
- year - the year
- Region - the city or region of the observation
- Total Volume - Total number of avocados sold
- 4046 - Total number of avocados with PLU 4046 sold
- 4225 - Total number of avocados with PLU 4225 sold
- 4770 - Total number of avocados with PLU 4770 sold


For this specific notebook let's use only:

- AveragePrice - the average price of a single avocado
- Total Volume - Total number of avocados sold
- 4046 - Total number of avocados with PLU 4046 sold
- 4225 - Total number of avocados with PLU 4225 sold
- 4770 - Total number of avocados with PLU 4770 sold

specifically average price as label (y) and the other columns as features

In [4]:
data = df[["Total Volume", "4046", "4225", "4770", "AveragePrice"]]

In [5]:
# perform normalization - usually this task should be performed for X_train and X_test
# in two different steps to avoid data leak

In [6]:
scaler = StandardScaler()
data = scaler.fit_transform(data)

In [7]:
# create training and test split 
X_train, X_test, y_train, y_test = train_test_split(data[:,:-1], data[:,-1], test_size=0.33, random_state=42)

In [8]:
print("Feautures dataset:",X_train.shape)
print("Label dataset:", y_train.shape)

Feautures dataset: (12226, 4)
Label dataset: (12226,)


## Define and compile Network

In [9]:
model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[4])])

Now it is possible to define the optimizer and the loss function that will be used

In [10]:
model.compile(optimizer='sgd', loss='mean_squared_error')

## Model training and predict

In [11]:
model.fit(X_train, y_train, epochs=15)

Epoch 1/15
383/383 [==============================] - 1s 1ms/step - loss: 1.0608
Epoch 2/15
383/383 [==============================] - 0s 1ms/step - loss: 0.9608
Epoch 3/15
383/383 [==============================] - 0s 1ms/step - loss: 0.9571
Epoch 4/15
383/383 [==============================] - 0s 1ms/step - loss: 0.9547
Epoch 5/15
383/383 [==============================] - 0s 1ms/step - loss: 0.9554
Epoch 6/15
383/383 [==============================] - 0s 1ms/step - loss: 0.9544
Epoch 7/15
383/383 [==============================] - 0s 1ms/step - loss: 0.9546
Epoch 8/15
383/383 [==============================] - 0s 1ms/step - loss: 0.9542
Epoch 9/15
383/383 [==============================] - 1s 1ms/step - loss: 0.9541
Epoch 10/15
383/383 [==============================] - 0s 1ms/step - loss: 0.9536
Epoch 11/15
383/383 [==============================] - 0s 1ms/step - loss: 0.9543
Epoch 12/15
383/383 [==============================] - 0s 1ms/step - loss: 0.9542
Epoch 13/15
383/383 [====

In [12]:
y_pred = model.predict(X_test)

## Estimate performances

In [13]:
from sklearn.metrics import mean_absolute_error
print("MAE:",mean_absolute_error(y_test, y_pred))

MAE: 0.7832520066951534
